# This file was generated by GoReleaser. DO NOT EDIT.
class Gojira < Formula
  desc "Save your time on Jira operation through the command line."
  homepage "https://github.com/leozhantw/gojira"
  version "1.2.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/leozhantw/gojira/releases/download/v1.2.0/gojira_1.2.0_Darwin_x86_64.tar.gz"
    sha256 "b6967f685169a8bf1c3c67251c0c62ff8dbe4a04e074ee5a20d85c427f389c9f"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/leozhantw/gojira/releases/download/v1.2.0/gojira_1.2.0_Linux_x86_64.tar.gz"
    sha256 "9ec1a9ba7b30743aebdd0bbb7ede13e5aa8d57404c8047d929139b1be8ec3906"
  end

  def install
    bin.install "gojira"
  end
end
