# This file was generated by GoReleaser. DO NOT EDIT.
class Gojira < Formula
  desc "Save your time on Jira operation through the command line."
  homepage "https://github.com/leozhantw/gojira"
  version "1.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/leozhantw/gojira/releases/download/v1.0.0/gojira_1.0.0_Darwin_x86_64.tar.gz"
    sha256 "31b8e6f7709e643e38416236f307343b18a96b9834ac5e87c4560ba04974e93a"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/leozhantw/gojira/releases/download/v1.0.0/gojira_1.0.0_Linux_x86_64.tar.gz"
    sha256 "5bc6bf089405e38f0ddb58b3c2b904f9f4363063f087a915f9efaaeb900ffd25"
  end

  def install
    bin.install "gojira"
  end
end
