# This file was generated by GoReleaser. DO NOT EDIT.
class Gojira < Formula
  desc "Save your time on Jira operation through the command line."
  homepage "https://github.com/leozhantw/gojira"
  version "1.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/leozhantw/gojira/releases/download/v1.1.0/gojira_1.1.0_Darwin_x86_64.tar.gz"
    sha256 "1c8714e4466c246964215f3909492f096d63b4ef819071800f25854bbda29629"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/leozhantw/gojira/releases/download/v1.1.0/gojira_1.1.0_Linux_x86_64.tar.gz"
    sha256 "5cfe593f23a6692bb64952d8609c60e871d4628da91ed9d0a19236f2b92b7914"
  end

  def install
    bin.install "gojira"
  end
end
